### ISSUE TITLE
Some docs on reuse?

### ISSUE THREAD

**Issue by adam-rocska** [stackb/ui.js#1]
Hi.

I stumbled upon this repo while searching for a thick client routing solution to integrate in our front-end system built using Bazel with Google Closure Toolkit.

I would like to give it a shot, but there's no dependency & toolchain resolver exposed & I couldn't even build it after a git clone, since it fails due to the `'//js/ui:app'` being commented out.

Any way & plans to make this solution more open & flexible for external reuse?

We could contrib' stuff in that case.

**Comment by pcj** [comment]
Apologies, I completely missed this issue.  I'll try and put together an example.

**Comment by adam-rocska** [comment]
@pcj Don't sweat it, sadly we took a different route 😞
